# Generated by Django 3.2 on 2021-11-03 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=30, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=40, verbose_name='last_name')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('birth_date', models.CharField(max_length=15, verbose_name='birth_date')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('password', models.CharField(max_length=30, verbose_name='password')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
