# Generated by Django 3.2 on 2021-11-03 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootcampwallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='birth_date',
            field=models.TextField(verbose_name='birth_date'),
        ),
        migrations.AlterField(
            model_name='users',
            name='first_name',
            field=models.TextField(verbose_name='first_name'),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_name',
            field=models.TextField(verbose_name='last_name'),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.TextField(verbose_name='password'),
        ),
    ]
