# Generated by Django 3.2 on 2021-11-03 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootcampwallet', '0002_auto_20211103_0019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='password',
        ),
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
