# Generated by Django 3.2 on 2021-11-03 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootcampwallet', '0003_auto_20211103_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.TextField(default=123, verbose_name='password'),
            preserve_default=False,
        ),
    ]
