# Generated by Django 3.2 on 2021-11-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootcampwallet', '0004_users_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='balance',
            field=models.FloatField(default=0.0, verbose_name='balance'),
            preserve_default=False,
        ),
    ]
