# Generated by Django 3.2 on 2021-11-12 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bootcampwallet', '0005_users_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_transaction', models.TextField(verbose_name='type_of_transaction')),
                ('secondary_email', models.EmailField(max_length=254, verbose_name='secondary_email')),
                ('value', models.FloatField(verbose_name='value')),
                ('date', models.DateField(verbose_name='date')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
    ]
