# Generated by Django 3.2 on 2021-11-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootcampwallet', '0006_transactions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='email',
        ),
        migrations.AddField(
            model_name='transactions',
            name='user_id',
            field=models.IntegerField(default=0, verbose_name='user_id'),
            preserve_default=False,
        ),
    ]
